"""Add badge models and user relationship

Revision ID: 8dc493c306c7
Revises:
Create Date: 2025-10-25 08:10:23.276626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <-- Keep this import

# revision identifiers, used by Alembic.
revision: str = '8dc493c306c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Alter columns (usually safe to keep)
    op.alter_column('farm', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('farm', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('farm', 'size_acres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # --- vvvv FIX: Comment out 'value' column addition vvvv ---
    # op.add_column('farmactivity', sa.Column('value', sa.Float(), nullable=True))
    # --- ^^^^ END FIX ^^^^ ---

    # --- vvvv FIX: Comment out 'unit' column addition vvvv ---
    # op.add_column('farmactivity', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # --- ^^^^ END FIX ^^^^ ---

    # Add operations for 'badge' and 'userbadge' tables if they belong in this migration
    # op.create_table('badge', ...)
    # op.create_index(op.f('ix_badge_name'), 'badge', ['name'], unique=True)
    # op.create_table('userbadge', ...)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- vvvv FIX: Comment out 'unit' column drop vvvv ---
    # op.drop_column('farmactivity', 'unit')
    # --- ^^^^ END FIX ^^^^ ---

    # --- vvvv FIX: Comment out 'value' column drop vvvv ---
    # op.drop_column('farmactivity', 'value')
    # --- ^^^^ END FIX ^^^^ ---

    # Alter columns for downgrade
    op.alter_column('farm', 'size_acres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False) # Adjust nullability as needed
    op.alter_column('farm', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False) # Adjust nullability as needed
    op.alter_column('farm', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False) # Adjust nullability as needed

    # Add drop_table commands if corresponding create_table exists in upgrade
    # op.drop_table('userbadge')
    # op.drop_index(op.f('ix_badge_name'), table_name='badge')
    # op.drop_table('badge')

    # ### end Alembic commands ###